// Generated by HybridApp.Core.Generators.TsStoreGenerator
// Do not edit manually
import { create } from 'zustand';

type PatchResult = { nextVm: any; changed: boolean };

function toCamel(value: string): string {
  if (!value) return value;
  return value.charAt(0).toLowerCase() + value.slice(1);
}

function getInstanceStoreKey(vmType: string): string {
  return `${toCamel(vmType)}Instances`;
}

function patchVmState(vmState: any, propName: string, value: any): PatchResult {
  const isPath = propName.includes('.') || propName.includes('[');
  const nextVm = { ...(vmState ?? {}) };
  if (!isPath) {
    const propKey = toCamel(propName);
    if (nextVm[propKey] === value) return { nextVm: vmState, changed: false };
    nextVm[propKey] = value;
    return { nextVm, changed: true };
  }
  let current: any = nextVm;
  const parts = propName.split(/[.\]\[]/g).filter(Boolean);
  for (let i = 0; i < parts.length - 1; i++) {
    const p = parts[i];
    const key = (i === 0 && !propName.startsWith('[')) ? toCamel(p) : p;
    if (current[key] === undefined || current[key] === null) return { nextVm: vmState, changed: false };
    const nextChild = Array.isArray(current[key]) ? [...current[key]] : { ...current[key] };
    current[key] = nextChild;
    current = nextChild;
  }
  const lastPart = parts[parts.length - 1];
  const lastKey = (parts.length === 1) ? toCamel(lastPart) : lastPart;
  if (current[lastKey] === value) return { nextVm: vmState, changed: false };
  current[lastKey] = value;
  return { nextVm, changed: true };
}

/**
 * 处理复杂嵌套对象和集合数据的示例 ViewModel
 */
export interface ComplexVM {
  /**
   * 设备全局配置信息
   */
  config: DeviceConfig;
  /**
   * 系统状态字典信息
   */
  statusInfo: { [key: string]: string };
  /**
   * 运行日志列表
   */
  logs: any;
}

/**
 * 相机视觉控制模块，处理曝光、增益等实时参数
 */
export interface VisionVM {
  /**
   * 曝光时间（毫秒）
   */
  exposure: number;
  /**
   * 模拟增益倍数
   */
  gain: number;
  /**
   * 是否正在运行图像处理算法
   */
  isRunning: boolean;
}

export interface DeviceConfig {
  internalCamera: CameraParams;
  /**
   * 设备型号名称
   */
  modelName: string;
}

export interface LogEntry {
  /**
   * 日志消息
   */
  message: string;
  /**
   * 日志级别
   */
  level: string;
}

export interface CameraParams {
  /**
   * 水平分辨率
   */
  resolutionX: number;
  /**
   * 垂直分辨率
   */
  resolutionY: number;
  /**
   * 支持的拍摄模式列表
   */
  supportedModes: string[];
}

export interface AppState {
  /**
   * 处理复杂嵌套对象和集合数据的示例 ViewModel
   */
  complexVM: ComplexVM;
  complexVMInstances: Record<string, ComplexVM>;
  /**
   * 相机视觉控制模块，处理曝光、增益等实时参数
   */
  visionVM: VisionVM;
  visionVMInstances: Record<string, VisionVM>;
}

export interface AppActions {
  updateStateFromBackend: (vmName: string, propName: string, value: any, vmType?: string) => void;
  setBackendState: (vmName: string, propName: string, value: any, vmType?: string) => void;
  setBackendInstanceState: (vmType: string, vmName: string, propName: string, value: any) => void;
  initFullState: (payload: any) => void;
}

export const useAppStore = create<AppState & AppActions>((set) => ({
  complexVM: {} as ComplexVM,
  complexVMInstances: {} as Record<string, ComplexVM>,
  visionVM: {} as VisionVM,
  visionVMInstances: {} as Record<string, VisionVM>,
  updateStateFromBackend: (vmName, propName, value, vmType) => set((state) => {
    const typeName = vmType ?? vmName;
    const stateKey = toCamel(typeName);
    const instanceStoreKey = getInstanceStoreKey(typeName);
    const currentInstance = (state as any)[instanceStoreKey]?.[vmName] ?? (vmName === typeName ? (state as any)[stateKey] : {});
    const { nextVm, changed } = patchVmState(currentInstance, propName, value);
    if (!changed) return state;
    const nextState: any = {
      ...state,
      [instanceStoreKey]: { ...((state as any)[instanceStoreKey] ?? {}), [vmName]: nextVm },
    };
    if (vmName === typeName) nextState[stateKey] = nextVm;
    return nextState;
  }),
  setBackendState: (vmName, propName, value, vmType) => {
    const typeName = vmType ?? vmName;
    const stateKey = toCamel(typeName);
    const instanceStoreKey = getInstanceStoreKey(typeName);
    let shouldUpdate = false;
    set((state) => {
      const currentInstance = (state as any)[instanceStoreKey]?.[vmName] ?? (vmName === typeName ? (state as any)[stateKey] : {});
      const { nextVm, changed } = patchVmState(currentInstance, propName, value);
      if (!changed) return state;
      shouldUpdate = true;
      const nextState: any = {
        ...state,
        [instanceStoreKey]: { ...((state as any)[instanceStoreKey] ?? {}), [vmName]: nextVm },
      };
      if (vmName === typeName) nextState[stateKey] = nextVm;
      return nextState;
    });
    if (shouldUpdate && (window as any).chrome?.webview) {
      (window as any).chrome.webview.postMessage({
        type: 'STATE_SET',
        payload: { vmType: typeName, vmName, propName, value }
      });
    }
  },
  setBackendInstanceState: (vmType, vmName, propName, value) => {
    useAppStore.getState().setBackendState(vmName, propName, value, vmType);
  },
  initFullState: (payload) => set((state) => {
    const response = payload?.instances ? payload : { state: payload };
    const newState: any = { ...state };
    if (Array.isArray(response.instances)) {
      for (const item of response.instances) {
        const vmType = item.vmType ?? item.vmName;
        const vmName = item.vmName ?? vmType;
        const stateKey = toCamel(vmType);
        const instanceStoreKey = getInstanceStoreKey(vmType);
        newState[instanceStoreKey] = { ...(newState[instanceStoreKey] ?? {}), [vmName]: item.state };
        if (vmName === vmType) newState[stateKey] = item.state;
      }
      return newState;
    }
    for (const key in response.state) {
      const stateKey = toCamel(key);
      const instanceStoreKey = getInstanceStoreKey(key);
      newState[stateKey] = response.state[key];
      newState[instanceStoreKey] = { ...(newState[instanceStoreKey] ?? {}), [key]: response.state[key] };
    }
    return newState;
  }),
}));

// ---- Command Invocation ----

const _pendingCommands = new Map<string, { resolve: (v: any) => void; reject: (e: any) => void }>();
let _commandIdCounter = 0;

// ---- Event Subscriptions ----
const _eventSubscribers = new Map<string, Set<(args: any) => void>>();

// Listen for messages from C# backend
if ((window as any).chrome?.webview) {
  (window as any).chrome.webview.addEventListener('message', (event: any) => {
    const data = event.data;
    if (data?.type === 'COMMAND_RESPONSE' && data.payload?.requestId) {
      const pending = _pendingCommands.get(data.payload.requestId);
      if (pending) {
        _pendingCommands.delete(data.payload.requestId);
        if (data.payload.success) { pending.resolve(data.payload.result); }
        else { pending.reject(new Error(data.payload.error || 'Command failed')); }
      }
    }
    else if (data?.type === 'BACKEND_EVENT' && data.payload) {
      const subs = _eventSubscribers.get(`${data.payload.vmName}_${data.payload.eventName}`);
      if (subs) {
        subs.forEach(cb => {
          try { cb(data.payload.args); } catch (e) { console.error(e); }
        });
      }
    }
  });
}

function invokeCommand(vmName: string, methodName: string, args?: Record<string, any>, vmType?: string): void {
  (window as any).chrome?.webview?.postMessage({
    type: 'COMMAND',
    payload: { vmType: vmType ?? vmName, vmName, methodName, args: args ?? {} }
  });
}

function invokeCommandAsync<T = any>(vmName: string, methodName: string, args?: Record<string, any>, vmType?: string): Promise<T> {
  const requestId = `cmd_${++_commandIdCounter}_${Date.now()}`;
  return new Promise<T>((resolve, reject) => {
    _pendingCommands.set(requestId, { resolve, reject });
    (window as any).chrome?.webview?.postMessage({
      type: 'COMMAND',
      payload: { vmType: vmType ?? vmName, vmName, methodName, args: args ?? {}, requestId }
    });
    // Timeout after 30 seconds
    setTimeout(() => {
      if (_pendingCommands.has(requestId)) {
        _pendingCommands.delete(requestId);
        reject(new Error(`Command ${vmName}.${methodName} timed out`));
      }
    }, 30000);
  });
}

/**
 * 切换运行状态
 * @param reason string
 */
export function VisionVM_ToggleRunning(reason: string): void {
  invokeCommand('VisionVM', 'ToggleRunning', { reason }, 'VisionVM');
}

export function VisionVM_ToggleRunningFor(vmName: string, reason: string): void {
  invokeCommand(vmName, 'ToggleRunning', { reason }, 'VisionVM');
}

/**
 * 获取当前视觉模块状态摘要
 * @param prefix string
 * @returns Promise<string>
 */
export function VisionVM_GetStatusSummary(prefix: string): Promise<string> {
  return invokeCommandAsync<string>('VisionVM', 'GetStatusSummary', { prefix }, 'VisionVM');
}

export function VisionVM_GetStatusSummaryFor(vmName: string, prefix: string): Promise<string> {
  return invokeCommandAsync<string>(vmName, 'GetStatusSummary', { prefix }, 'VisionVM');
}

