// Generated by HybridApp.Core.Generators.TsStoreGenerator
// Do not edit manually
import { create } from 'zustand';

/**
 * CNC刀具路径控制，管理NC文件的加载和切换
 */
export interface CncPathVM {
  /**
   * 当前加载的NC文件名
   */
  currentFile: string;
  /**
   * 当前NC文件的GCode内容
   */
  gCodeContent: string;
}

/**
 * CNC设备运行状态数据，包含进给、主轴、各轴位置等
 */
export interface CncStatusVM {
  /**
   * 进给速度 (mm/min)
   */
  feedRate: number;
  /**
   * 主轴转速 (RPM)
   */
  spindleSpeed: number;
  /**
   * 当前刀号
   */
  toolNumber: number;
  /**
   * 运转状态 (如：运行中、停止、进给保持、报警)
   */
  runningState: string;
  /**
   * X轴位置
   */
  posX: number;
  /**
   * Y轴位置
   */
  posY: number;
  /**
   * Z轴位置
   */
  posZ: number;
  /**
   * A轴位置
   */
  posA: number;
  /**
   * B轴位置
   */
  posB: number;
  /**
   * C轴位置
   */
  posC: number;
}

/**
 * 全局机器状态，负责管理整机报警和提示信息
 */
export interface MachineVM {
  /**
   * 当前是否存在未清除的报警
   */
  hasActiveAlarm: boolean;
  /**
   * 当前报警的详情内容
   */
  currentAlarm: AlarmPayload;
  /**
   * 当前是否存在未清除的提示
   */
  hasActiveInfo: boolean;
  /**
   * 当前提示的详情内容
   */
  currentInfo: AlarmPayload;
  /**
   * 用户Sqlite本地数据库路径
   */
  sqliteDbPath: string;
}

/**
 * 物料信息展示数据层
 */
export interface MaterialVM {
  /**
   * 各个工位的物料详情集合
   */
  materials: any;
}

/**
 * 生产监控指标数据，包含投入产出、运行时间和稼动率等
 */
export interface MonitorVM {
  /**
   * 投入数
   */
  inputCount: number;
  /**
   * 产出数
   */
  outputCount: number;
  /**
   * 运行时间（HH:mm:ss格式）
   */
  runningTime: string;
  /**
   * 停机时间（HH:mm:ss格式）
   */
  downTime: string;
  /**
   * 稼动率（0-100）
   */
  utilization: number;
  /**
   * 是否正在生产
   */
  isRunning: boolean;
}

/**
 * 生产数据统计及历史查询ViewModel
 */
export interface ProduceDataVM {
}

/**
 * 刀具管理数据模型
 */
export interface ToolVM {
  /**
   * 36把刀的集合
   */
  tools: any;
  /**
   * 是否拥有寿命管理模块权限
   */
  hasLifeModule: boolean;
  /**
   * 是否拥有对刀管理模块权限
   */
  hasCalibrationModule: boolean;
  /**
   * 是否拥有刀补管理模块权限
   */
  hasCompensationModule: boolean;
}

/**
 * 矩形转盘控制，支持X/Y方向独立工位数和旋转方向控制
 */
export interface TurntableVM {
  /**
   * 当前步进位置
   */
  step: number;
  /**
   * X方向单边工位数
   */
  xCount: number;
  /**
   * Y方向单边工位数
   */
  yCount: number;
  /**
   * 0号工位（同心圆标记）的物理索引位置
   */
  zeroStationIndex: number;
  /**
   * 工位排布是否为顺时针方向
   */
  isClockwise: boolean;
  /**
   * 所有工位的状态及提示信息集合
   */
  stations: any;
  /**
   * 旋转方向：1=正转(顺时针运转), -1=反转(逆时针运转)
   */
  rotateDirection: number;
}

export interface AlarmPayload {
  alarmId: string;
  level: string;
  message: string;
  timestamp: string;
}

export interface MaterialItem {
  /**
   * 工位状态
   */
  stationState: string;
  /**
   * 工位序号
   */
  station: number;
  /**
   * 优先级
   */
  priority: string;
  /**
   * 毛长
   */
  blankLength: number;
  /**
   * 毛宽
   */
  blankWidth: number;
  /**
   * 加工文件
   */
  ncFile: string;
  /**
   * 分中
   */
  centerDivide: number;
  /**
   * 偏值Z
   */
  offsetZ: number;
  /**
   * 角度
   */
  angle: number;
  /**
   * 产品长
   */
  productLength: number;
  /**
   * 产品宽
   */
  productWidth: number;
  /**
   * 阵列数
   */
  arrayCount: number;
  /**
   * 阵列间
   */
  arraySpacing: number;
  /**
   * 是否光刀
   */
  isLightCut: boolean;
  /**
   * 最小Z值
   */
  minZValue: number;
}

export interface FormResult {
  success: boolean;
  message: string;
}

export interface ProduceData {
  fileName: string;
  count: number;
  startTime: string;
  endTime: string;
  timeSpanMinute: number;
}

export interface DailyProduceStat {
  dateString: string;
  totalCount: number;
  averageTimeSpan: number;
}

export interface ToolItem {
  /**
   * 刀号
   */
  id: number;
  /**
   * 别名
   */
  name: string;
  /**
   * 寿命上限 (小时)
   */
  maxLifetime: number;
  /**
   * 当前已使用时长 (小时)
   */
  usedLifetime: number;
  /**
   * 已切换次数
   */
  switchCount: number;
  /**
   * 最大允许切换次数
   */
  maxSwitchCount: number;
  /**
   * 上一次更换刀具时间
   */
  lastReplacedAt: string;
  /**
   * 上一次对刀时间
   */
  lastCalibratedAt: string;
  /**
   * 对刀时间间隔 (小时)
   */
  calibrationInterval: number;
  /**
   * 刀补D (全局)
   */
  compensationD: number;
  /**
   * 刀补H (全局)
   */
  compensationH: number;
}

export interface StationItem {
  /**
   * 工位状态（0=空闲,1=待加工,2=加工中,3=加工完成,4=未知）
   */
  state: number;
  /**
   * 工位提示信息
   */
  toolTip: string;
}

export interface AppState {
  /**
   * CNC刀具路径控制，管理NC文件的加载和切换
   */
  cncPathVM: CncPathVM;
  /**
   * CNC设备运行状态数据，包含进给、主轴、各轴位置等
   */
  cncStatusVM: CncStatusVM;
  /**
   * 全局机器状态，负责管理整机报警和提示信息
   */
  machineVM: MachineVM;
  /**
   * 物料信息展示数据层
   */
  materialVM: MaterialVM;
  /**
   * 生产监控指标数据，包含投入产出、运行时间和稼动率等
   */
  monitorVM: MonitorVM;
  /**
   * 生产数据统计及历史查询ViewModel
   */
  produceDataVM: ProduceDataVM;
  /**
   * 刀具管理数据模型
   */
  toolVM: ToolVM;
  /**
   * 矩形转盘控制，支持X/Y方向独立工位数和旋转方向控制
   */
  turntableVM: TurntableVM;
}

export interface AppActions {
  updateStateFromBackend: (vmName: string, propName: string, value: any) => void;
  setBackendState: (vmName: string, propName: string, value: any) => void;
  initFullState: (fullState: AppState) => void;
}

export const useAppStore = create<AppState & AppActions>((set) => ({
  cncPathVM: {} as CncPathVM,
  cncStatusVM: {} as CncStatusVM,
  machineVM: {} as MachineVM,
  materialVM: {} as MaterialVM,
  monitorVM: {} as MonitorVM,
  produceDataVM: {} as ProduceDataVM,
  toolVM: {} as ToolVM,
  turntableVM: {} as TurntableVM,
  updateStateFromBackend: (vmName, propName, value) => set((state) => {
    const stateKey = vmName.charAt(0).toLowerCase() + vmName.slice(1);
    const propKey = propName.charAt(0).toLowerCase() + propName.slice(1);
    if (!(stateKey in state)) return state;
    return { ...state, [stateKey]: { ...(state as any)[stateKey], [propKey]: value } };
  }),
  setBackendState: (vmName, propName, value) => {
    const stateKey = vmName.charAt(0).toLowerCase() + vmName.slice(1);
    const isPath = propName.includes('.') || propName.includes('[');
    let shouldUpdate = false;
    // 1. Update Local Store (Simple heuristic for pure root props vs deep paths)
    if (!isPath) {
      const propKey = propName.charAt(0).toLowerCase() + propName.slice(1);
      set((state) => {
        const currentState = (state as any)[stateKey];
        if (currentState && currentState[propKey] === value) return state;
        shouldUpdate = true;
        return { ...state, [stateKey]: { ...currentState, [propKey]: value } };
      });
    } else {
      // Support deep property update locally using mutative approach
      set((state) => {
         const newState = { ...state };
         const vmState = { ...(newState as any)[stateKey] };
         // Basic path parser for local immediate response
         let current: any = vmState;
         const parts = propName.split(/[.\]\[]/g).filter(Boolean);
         for (let i = 0; i < parts.length - 1; i++) {
             const p = parts[i];
             const key = (i === 0 && !propName.startsWith('[')) ? (p.charAt(0).toLowerCase() + p.slice(1)) : p;
             if (current[key] !== undefined) current = current[key];
         }
         const lastPart = parts[parts.length - 1];
         const lastKey = (parts.length === 1) ? (lastPart.charAt(0).toLowerCase() + lastPart.slice(1)) : lastPart;
         if (current[lastKey] === value) return state;
         shouldUpdate = true;
         current[lastKey] = value;
         newState[stateKey as keyof AppState] = vmState as any;
         return newState;
      });
    }
    // 2. Push to C# Backend only if value changed
    if (shouldUpdate && (window as any).chrome?.webview) {
      (window as any).chrome.webview.postMessage({
        type: 'STATE_SET',
        payload: { vmName, propName, value }
      });
    }
  },
  initFullState: (fullState) => set((state) => {
    const newState: any = { ...state };
    for (const key in fullState) {
        const stateKey = key.charAt(0).toLowerCase() + key.slice(1);
        newState[stateKey] = (fullState as any)[key];
    }
    return newState;
  }),
}));

// ---- Command Invocation ----

const _pendingCommands = new Map<string, { resolve: (v: any) => void; reject: (e: any) => void }>();
let _commandIdCounter = 0;

// ---- Event Subscriptions ----
const _eventSubscribers = new Map<string, Set<(args: any) => void>>();

// Listen for messages from C# backend
if ((window as any).chrome?.webview) {
  (window as any).chrome.webview.addEventListener('message', (event: any) => {
    const data = event.data;
    if (data?.type === 'COMMAND_RESPONSE' && data.payload?.requestId) {
      const pending = _pendingCommands.get(data.payload.requestId);
      if (pending) {
        _pendingCommands.delete(data.payload.requestId);
        if (data.payload.success) { pending.resolve(data.payload.result); }
        else { pending.reject(new Error(data.payload.error || 'Command failed')); }
      }
    }
    else if (data?.type === 'BACKEND_EVENT' && data.payload) {
      const subs = _eventSubscribers.get(`${data.payload.vmName}_${data.payload.eventName}`);
      if (subs) {
        subs.forEach(cb => {
          try { cb(data.payload.args); } catch (e) { console.error(e); }
        });
      }
    }
  });
}

function invokeCommand(vmName: string, methodName: string, args?: Record<string, any>): void {
  (window as any).chrome?.webview?.postMessage({
    type: 'COMMAND',
    payload: { vmName, methodName, args: args ?? {} }
  });
}

function invokeCommandAsync<T = any>(vmName: string, methodName: string, args?: Record<string, any>): Promise<T> {
  const requestId = `cmd_${++_commandIdCounter}_${Date.now()}`;
  return new Promise<T>((resolve, reject) => {
    _pendingCommands.set(requestId, { resolve, reject });
    (window as any).chrome?.webview?.postMessage({
      type: 'COMMAND',
      payload: { vmName, methodName, args: args ?? {}, requestId }
    });
    // Timeout after 30 seconds
    setTimeout(() => {
      if (_pendingCommands.has(requestId)) {
        _pendingCommands.delete(requestId);
        reject(new Error(`Command ${vmName}.${methodName} timed out`));
      }
    }, 30000);
  });
}

/**
 * 从指定路径加载NC文件
 * @param filePath string
 * @returns Promise<string>
 */
export function CncPathVM_LoadNcFile(filePath: string): Promise<string> {
  return invokeCommandAsync<string>('CncPathVM', 'LoadNcFile', { filePath });
}

/**
 * 当机器发生新报警时触发
 * @param callback Function to be called when the event is triggered
 * @returns Function to unsubscribe from the event
 */
export function onMachineVM_OnNewAlarm(callback: (args: AlarmPayload) => void): () => void {
  const key = 'MachineVM_OnNewAlarm';
  if (!_eventSubscribers.has(key)) {
    _eventSubscribers.set(key, new Set());
  }
  _eventSubscribers.get(key)!.add(callback as any);
  return () => {
    const subs = _eventSubscribers.get(key);
    if (subs) {
      subs.delete(callback as any);
      if (subs.size === 0) _eventSubscribers.delete(key);
    }
  };
}

/**
 * 当机器发生新提示时触发
 * @param callback Function to be called when the event is triggered
 * @returns Function to unsubscribe from the event
 */
export function onMachineVM_OnNewInfo(callback: (args: AlarmPayload) => void): () => void {
  const key = 'MachineVM_OnNewInfo';
  if (!_eventSubscribers.has(key)) {
    _eventSubscribers.set(key, new Set());
  }
  _eventSubscribers.get(key)!.add(callback as any);
  return () => {
    const subs = _eventSubscribers.get(key);
    if (subs) {
      subs.delete(callback as any);
      if (subs.size === 0) _eventSubscribers.delete(key);
    }
  };
}

/**
 * 弹出文件选择对话框选择NC文件
 * @returns Promise<string>
 */
export function MaterialVM_SelectNcFile(): Promise<string> {
  return invokeCommandAsync<string>('MaterialVM', 'SelectNcFile', {});
}

/**
 * 校验并应用工位物料行数据的修改
 * @param stationIndex number
 * @param draftData MaterialItem
 * @returns Promise<FormResult>
 */
export function MaterialVM_ApplyMaterialChanges(stationIndex: number, draftData: MaterialItem): Promise<FormResult> {
  return invokeCommandAsync<FormResult>('MaterialVM', 'ApplyMaterialChanges', { stationIndex, draftData });
}

/**
 * 批量粘贴并应用多个工位的数据
 * @param stationIndices number[]
 * @param templateData MaterialItem
 * @returns Promise<FormResult>
 */
export function MaterialVM_PasteMaterialChanges(stationIndices: number[], templateData: MaterialItem): Promise<FormResult> {
  return invokeCommandAsync<FormResult>('MaterialVM', 'PasteMaterialChanges', { stationIndices, templateData });
}

/**
 * 当稼动率过低时触发警告
 * @param callback Function to be called when the event is triggered
 * @returns Function to unsubscribe from the event
 */
export function onMonitorVM_UtilizationWarning(callback: (args: string) => void): () => void {
  const key = 'MonitorVM_UtilizationWarning';
  if (!_eventSubscribers.has(key)) {
    _eventSubscribers.set(key, new Set());
  }
  _eventSubscribers.get(key)!.add(callback as any);
  return () => {
    const subs = _eventSubscribers.get(key);
    if (subs) {
      subs.delete(callback as any);
      if (subs.size === 0) _eventSubscribers.delete(key);
    }
  };
}

/**
 * 根据时间范围查询班次/详细的生产数据记录
 * @param startTime string
 * @param endTime string
 * @returns Promise<ProduceData[]>
 */
export function ProduceDataVM_QueryProduceData(startTime: string, endTime: string): Promise<ProduceData[]> {
  return invokeCommandAsync<ProduceData[]>('ProduceDataVM', 'QueryProduceData', { startTime, endTime });
}

/**
 * 查询指定时间范围内每天的加工数量统计，用于图表展示
 * @param startTime string
 * @param endTime string
 * @returns Promise<DailyProduceStat[]>
 */
export function ProduceDataVM_QueryDailyStatistics(startTime: string, endTime: string): Promise<DailyProduceStat[]> {
  return invokeCommandAsync<DailyProduceStat[]>('ProduceDataVM', 'QueryDailyStatistics', { startTime, endTime });
}

/**
 * 用于调试：初始化自动生成假数据避免表不存在
 */
export function ProduceDataVM_MockInitDataIfTableNotExists(): void {
  invokeCommand('ProduceDataVM', 'MockInitDataIfTableNotExists', {});
}

/**
 * 修改指定刀具的各项可编辑参数
 * @param index number
 * @param draftData ToolItem
 * @returns Promise<FormResult>
 */
export function ToolVM_ApplyToolChanges(index: number, draftData: ToolItem): Promise<FormResult> {
  return invokeCommandAsync<FormResult>('ToolVM', 'ApplyToolChanges', { index, draftData });
}

/**
 * 批量粘贴并应用多个刀具的数据
 * @param indices number[]
 * @param templateData ToolItem
 * @returns Promise<FormResult>
 */
export function ToolVM_PasteToolChanges(indices: number[], templateData: ToolItem): Promise<FormResult> {
  return invokeCommandAsync<FormResult>('ToolVM', 'PasteToolChanges', { indices, templateData });
}

/**
 * 批量手动对刀，更新最后对刀时间
 * @param indices number[]
 * @returns Promise<FormResult>
 */
export function ToolVM_CalibrateTools(indices: number[]): Promise<FormResult> {
  return invokeCommandAsync<FormResult>('ToolVM', 'CalibrateTools', { indices });
}

/**
 * 正转一步
 */
export function TurntableVM_RotateForward(): void {
  invokeCommand('TurntableVM', 'RotateForward', {});
}

/**
 * 反转一步
 */
export function TurntableVM_RotateBackward(): void {
  invokeCommand('TurntableVM', 'RotateBackward', {});
}

/**
 * 设置自动旋转方向：0=停止, 1=正转, -1=反转
 * @param direction number
 */
export function TurntableVM_SetAutoRotate(direction: number): void {
  invokeCommand('TurntableVM', 'SetAutoRotate', { direction });
}

/**
 * 设置指定工位的状态
 * @param index number
 * @param state number
 */
export function TurntableVM_SetStationState(index: number, state: number): void {
  invokeCommand('TurntableVM', 'SetStationState', { index, state });
}

/**
 * 设置指定工位的ToolTip提示文本
 * @param index number
 * @param toolTip string
 */
export function TurntableVM_SetStationToolTip(index: number, toolTip: string): void {
  invokeCommand('TurntableVM', 'SetStationToolTip', { index, toolTip });
}

