// Generated by HybridApp.Core.Generators.TsStoreGenerator
// Do not edit manually
import { create } from 'zustand';

/**
 * CNC刀具路径控制，管理NC文件的加载和切换
 */
export interface CncPathVM {
  /**
   * 当前加载的NC文件名
   */
  currentFile: string;
  /**
   * 当前NC文件的GCode内容
   */
  gCodeContent: string;
}

/**
 * 物料信息展示数据层
 */
export interface MaterialVM {
  /**
   * 各个工位的物料详情集合
   */
  materials: any;
}

/**
 * 生产监控指标数据，包含投入产出、运行时间和稼动率等
 */
export interface MonitorVM {
  /**
   * 投入数
   */
  inputCount: number;
  /**
   * 产出数
   */
  outputCount: number;
  /**
   * 运行时间（HH:mm:ss格式）
   */
  runningTime: string;
  /**
   * 停机时间（HH:mm:ss格式）
   */
  downTime: string;
  /**
   * 稼动率（0-100）
   */
  utilization: number;
  /**
   * 是否正在生产
   */
  isRunning: boolean;
}

/**
 * 矩形转盘控制，支持X/Y方向独立工位数和旋转方向控制
 */
export interface TurntableVM {
  /**
   * 当前步进位置
   */
  step: number;
  /**
   * X方向单边工位数
   */
  xCount: number;
  /**
   * Y方向单边工位数
   */
  yCount: number;
  /**
   * 0号工位（同心圆标记）的物理索引位置
   */
  zeroStationIndex: number;
  /**
   * 工位排布是否为顺时针方向
   */
  isClockwise: boolean;
  /**
   * 所有工位的状态及提示信息集合
   */
  stations: any;
  /**
   * 旋转方向：1=正转(顺时针运转), -1=反转(逆时针运转)
   */
  rotateDirection: number;
}

export interface MaterialItem {
  /**
   * 工位状态
   */
  stationState: string;
  /**
   * 工位序号
   */
  station: number;
  /**
   * 优先级
   */
  priority: string;
  /**
   * 毛长
   */
  blankLength: number;
  /**
   * 毛宽
   */
  blankWidth: number;
  /**
   * 加工文件
   */
  ncFile: string;
  /**
   * 分中
   */
  centerDivide: number;
  /**
   * 偏值Z
   */
  offsetZ: number;
  /**
   * 角度
   */
  angle: number;
  /**
   * 产品长
   */
  productLength: number;
  /**
   * 产品宽
   */
  productWidth: number;
  /**
   * 阵列数
   */
  arrayCount: number;
  /**
   * 阵列间
   */
  arraySpacing: number;
}

export interface StationItem {
  /**
   * 工位状态（0=空闲,1=待加工,2=加工中,3=加工完成,4=未知）
   */
  state: number;
  /**
   * 工位提示信息
   */
  toolTip: string;
}

export interface AppState {
  /**
   * CNC刀具路径控制，管理NC文件的加载和切换
   */
  cncPathVM: CncPathVM;
  /**
   * 物料信息展示数据层
   */
  materialVM: MaterialVM;
  /**
   * 生产监控指标数据，包含投入产出、运行时间和稼动率等
   */
  monitorVM: MonitorVM;
  /**
   * 矩形转盘控制，支持X/Y方向独立工位数和旋转方向控制
   */
  turntableVM: TurntableVM;
}

export interface AppActions {
  updateStateFromBackend: (vmName: string, propName: string, value: any) => void;
  setBackendState: (vmName: string, propName: string, value: any) => void;
  initFullState: (fullState: AppState) => void;
}

export const useAppStore = create<AppState & AppActions>((set) => ({
  cncPathVM: {} as CncPathVM,
  materialVM: {} as MaterialVM,
  monitorVM: {} as MonitorVM,
  turntableVM: {} as TurntableVM,
  updateStateFromBackend: (vmName, propName, value) => set((state) => {
    const stateKey = vmName.charAt(0).toLowerCase() + vmName.slice(1);
    const propKey = propName.charAt(0).toLowerCase() + propName.slice(1);
    if (!(stateKey in state)) return state;
    return { ...state, [stateKey]: { ...(state as any)[stateKey], [propKey]: value } };
  }),
  setBackendState: (vmName, propName, value) => {
    const stateKey = vmName.charAt(0).toLowerCase() + vmName.slice(1);
    const isPath = propName.includes('.') || propName.includes('[');
    // 1. Update Local Store (Simple heuristic for pure root props vs deep paths)
    if (!isPath) {
      const propKey = propName.charAt(0).toLowerCase() + propName.slice(1);
      set((state) => ({ ...state, [stateKey]: { ...(state as any)[stateKey], [propKey]: value } }));
    } else {
      // Support deep property update locally using mutative approach to avoid complex lodash.set in generated code
      // Alternatively backend's subsequent STATE_SYNC will overwrite this with the final data.
      set((state) => {
         const newState = { ...state };
         const vmState = { ...(newState as any)[stateKey] };
         // Basic path parser for local immediate response
         let current: any = vmState;
         const parts = propName.split(/[.\]\[]/g).filter(Boolean);
         for (let i = 0; i < parts.length - 1; i++) {
             const p = parts[i];
             // lower case first level if needed
             const key = (i === 0 && !propName.startsWith('[')) ? (p.charAt(0).toLowerCase() + p.slice(1)) : p;
             if (current[key] !== undefined) current = current[key];
         }
         const lastPart = parts[parts.length - 1];
         const lastKey = (parts.length === 1) ? (lastPart.charAt(0).toLowerCase() + lastPart.slice(1)) : lastPart;
         current[lastKey] = value;
         newState[stateKey as keyof AppState] = vmState as any;
         return newState;
      });
    }
    // 2. Push to C# Backend
    if ((window as any).chrome?.webview) {
      (window as any).chrome.webview.postMessage({
        type: 'STATE_SET',
        payload: { vmName, propName, value }
      });
    }
  },
  initFullState: (fullState) => set((state) => {
    const newState: any = { ...state };
    for (const key in fullState) {
        const stateKey = key.charAt(0).toLowerCase() + key.slice(1);
        newState[stateKey] = (fullState as any)[key];
    }
    return newState;
  }),
}));

// ---- Command Invocation ----

const _pendingCommands = new Map<string, { resolve: (v: any) => void; reject: (e: any) => void }>();
let _commandIdCounter = 0;

// Listen for command responses from C# backend
if ((window as any).chrome?.webview) {
  (window as any).chrome.webview.addEventListener('message', (event: any) => {
    const data = event.data;
    if (data?.type === 'COMMAND_RESPONSE' && data.payload?.requestId) {
      const pending = _pendingCommands.get(data.payload.requestId);
      if (pending) {
        _pendingCommands.delete(data.payload.requestId);
        if (data.payload.success) { pending.resolve(data.payload.result); }
        else { pending.reject(new Error(data.payload.error || 'Command failed')); }
      }
    }
  });
}

function invokeCommand(vmName: string, methodName: string, args?: Record<string, any>): void {
  (window as any).chrome?.webview?.postMessage({
    type: 'COMMAND',
    payload: { vmName, methodName, args: args ?? {} }
  });
}

function invokeCommandAsync<T = any>(vmName: string, methodName: string, args?: Record<string, any>): Promise<T> {
  const requestId = `cmd_${++_commandIdCounter}_${Date.now()}`;
  return new Promise<T>((resolve, reject) => {
    _pendingCommands.set(requestId, { resolve, reject });
    (window as any).chrome?.webview?.postMessage({
      type: 'COMMAND',
      payload: { vmName, methodName, args: args ?? {}, requestId }
    });
    // Timeout after 30 seconds
    setTimeout(() => {
      if (_pendingCommands.has(requestId)) {
        _pendingCommands.delete(requestId);
        reject(new Error(`Command ${vmName}.${methodName} timed out`));
      }
    }, 30000);
  });
}

/**
 * 从指定路径加载NC文件
 * @param filePath string
 * @returns Promise<string>
 */
export function CncPathVM_LoadNcFile(filePath: string): Promise<string> {
  return invokeCommandAsync<string>('CncPathVM', 'LoadNcFile', { filePath });
}

/**
 * 弹出文件选择对话框选择NC文件
 * @returns Promise<string>
 */
export function MaterialVM_SelectNcFile(): Promise<string> {
  return invokeCommandAsync<string>('MaterialVM', 'SelectNcFile', {});
}

/**
 * 正转一步
 */
export function TurntableVM_RotateForward(): void {
  invokeCommand('TurntableVM', 'RotateForward', {});
}

/**
 * 反转一步
 */
export function TurntableVM_RotateBackward(): void {
  invokeCommand('TurntableVM', 'RotateBackward', {});
}

/**
 * 设置自动旋转方向：0=停止, 1=正转, -1=反转
 * @param direction number
 */
export function TurntableVM_SetAutoRotate(direction: number): void {
  invokeCommand('TurntableVM', 'SetAutoRotate', { direction });
}

/**
 * 设置指定工位的状态
 * @param index number
 * @param state number
 */
export function TurntableVM_SetStationState(index: number, state: number): void {
  invokeCommand('TurntableVM', 'SetStationState', { index, state });
}

/**
 * 设置指定工位的ToolTip提示文本
 * @param index number
 * @param toolTip string
 */
export function TurntableVM_SetStationToolTip(index: number, toolTip: string): void {
  invokeCommand('TurntableVM', 'SetStationToolTip', { index, toolTip });
}

